### ISSUE TITLE
Compilation issue in Visual C compiler

### ISSUE THREAD

**Issue by marcus905** [rickardp/splitstream#7]
The library fails to compile in Windows due to a bad intializer in splitstream_py.c:106.

According to the python documentation at https://docs.python.org/2/extending/newtypes.html the line should be 

`PyVarObject_HEAD_INIT(NULL, 0)`
instead of
`PyVarObject_HEAD_INIT(&PyType_Type, 0)`

to avoid this issue.

I can send a pull request for this change, if you want.

**Comment by rickardp** [comment]
fixed by #9
